export default class PayrollList {
    constructor(data = {}) {
        this.amount                 = data.amount || ''
        this.applyOvertime          = data.applyOvertime || false,
        this.bank                   = data.bank || {},
        this.benefitExchange        = data.benefitExchange || 0,
        this.benefitAccount         = data.benefitAccount || 0,
        this.currency               = data.currency || {},
        this.currencyKHM            = data.currencyKHM || '',
        this.date                   = data.date || '',
        this.deduction              = data.deduction || 0,
        this.deduction2             = data.deduction2 || 0,
        this.deductionExchange      = data.deductionExchange || 0,
        this.employeeId             = data.employeeId || '',
        this.employee_id            = data.employee_id || '',
        this.employeeUuid           = data.employeeUuid || '',
        this.employeeName           = data.employeeName || '',
        this.gender                 = data.gender || '',
        this.exchangeRate           = data.exchangeRate || 0,
        this.grossSalary            = data.grossSalary || 0,
        this.location               = data.location || {},
        this.minorChildrenAmount    = data.minorChildrenAmount || 0,
        this.netPay                 = data.netPay || 0,
        this.netSalary              = data.netSalary || 0,
        this.netPayExchange         = data.netPayExchange || 0,
        this.natureContract         = data.natureContract || {},
        this.natureEmployee         = data.natureEmployee || {},
        this.overTime               = data.overTime || 0,
        this.overTimeHoliday        = data.overTimeHoliday || 0,
        this.overTimeWeekend        = data.overTimeWeekend || 0,
        this.overTimeNight          = data.overTimeNight || 0,
        this.period                 = data.period || {},
        this.payrollComponent       = data.payrollComponent || '',
        this.position               = data.position || {},
        this.paidHours              = data.paidHours || 0,
        this.paymentMethod          = data.paymentMethod || {},
        this.payrollLiabilitie      = data.payrollLiabilitie || {},
        this.salary                 = data.salary || 0,
        this.salary1                = data.salary1 || 0,
        this.salary2                = data.salary2 || 0,
        this.salary3                = data.salary3 || 0,
        this.salaryType             = data.salaryType || {},
        this.salaryExchange         = data.salaryExchange || 0,
        this.segment                = data.segment || [],
        this.status                 = data.status || 0,
        this.salaryBase             = data.salaryBase || 0,
        this.spouse                 = data.spouse || 0,
        this.spouseAmount           = data.spouseAmount || 0,
        this.totalBenefit           = data.totalBenefit || 0,
        this.taxBenefitExchange     = data.taxBenefitExchange || 0,
        this.taxBenefit             = data.taxBenefit || 0,
        this.taxRate                = data.taxRate || 0,
        this.taxRateKHM             = data.taxRateKHM || 0,
        this.taxSalaryUS            = data.taxSalaryUS || 0,
        this.taxSalary              = data.taxSalary || 0,
        this.totalWorkinghours      = data.totalWorkinghours || 0,
        this.workDay                = data.workDay || 0,
        this.workingHours           = data.workingHours || 0,
        this.spouseNatureEmployee   = data.spouseNatureEmployee || '',
        this.workingStatus          = data.workingStatus || '',
        this.spouseGender           = data.spouseGender || '',
        this.noOfChildren           = data.noOfChildren || 0
    }
    constuct(data) {
        this.constructor(data);
    }
}